theme: jekyll-theme-slate
title: Goose Org-Chart Orchestrator
description: Privacy-First Multi-Agent AI Orchestration Framework
show_downloads: true
github:
  repository_url: https://github.com/JEFH507/org-chart-goose-orchestrator
  is_project_page: true
  owner_name: JEFH507
  owner_url: https://github.com/JEFH507
